apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: aurora
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: rabbitmq
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
